eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8904
spring:
    application:
        name: service-zuul
zuul:
  routes:
    ribbo:
      path: /api-ribbon/**
      serviceId: Service-Ribbon
    feign:
      path: /api-feign/**
      serviceId: Service-Feign
    App:
      path: /api-app/**
      serviceId: App


#简单配置两个路由， 一个路由到ribbon，一个路由到feign；
#由于都注册到eureka服务中心，所以都用通过serviceId (spring.application.name)来发现服务具体地址，
 #path是路由的地址映射关系