eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
server:
    port: 8904
spring:
    application:
        name: service-zuul
zuul:
  routes:
    app-service-web:
      path: /app-service-web/**
      serviceId: app-service-web


#简单配置两个路由， 一个路由到ribbon，一个路由到feign；
#由于都注册到eureka服务中心，所以都用通过serviceId (spring.application.name)来发现服务具体地址，
 #path是路由的地址映射关系